# Generated by Django 5.2.7 on 2025-12-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
