# Generated by Django 5.2.7 on 2025-12-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Seller',
        ),
    ]