# Generated by Django 5.2.7 on 2025-12-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_supplier_to_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='seller',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Comissão'),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
