# Generated by Django 5.2.7 on 2025-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_commission_rate_sale_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa de Comissão'),
        ),
    ]
