# Generated by Django 5.2.7 on 2025-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_saleitem_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='lote',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote'),
        ),
    ]
